language: python
python: 2.7
install: pip install tox coveralls
script: tox -e $TOX_ENV
after_success: coveralls
before_script:
    - cp t_overrides.travis.py t_overrides.py
    - psql -U postgres -c "DROP DATABASE IF EXISTS multigtfs"
    - psql -U postgres -c "CREATE DATABASE multigtfs"
    - psql -U postgres -d multigtfs -c "CREATE EXTENSION IF NOT EXISTS postgis; CREATE EXTENSION IF NOT EXISTS postgis_topology;"
env:
    - TOX_ENV=py27-django15-south08-postgis
    - TOX_ENV=py27-django16-south08-postgis
    - TOX_ENV=py34-django16-south08-postgis
